name: 'PR Deployer'
description: '"ChatOps" deployer using terraform'
inputs:
  gh_comment_token:
    description: 'The token used to add comments (does not need to be PAT)'
    required: true
  gh_pat_token:
    description: 'The token used to read private terraform modules'
    required: true
  gh_org_name:
    description: 'The organization name where private terraform modules are located'
    required: true
  terraform_backend:
    description: 'choose a terraform backend. Choices are "tfc" (default) or "s3"'
    default: tfc
  terraform_cloud_api_token:
    description: 'A token for Terraform cloud. required for TFC backend'
  terraform_org:
    description: 'The Terraform cloud organization. required for TFC backend'
  aws_access_id:
    description: 'AWS access key id for accessing tfstate s3/dynamodb. required for S3 backend.'
  aws_secret_key:
    description: 'AWS secret key for accessing tfstate s3/dynamodb. required for S3 backend'
  s3_bucket:
    description: 's3 bucket for storing tfstate. required for S3 backend'
  s3_dynamodb_table:
    description: 'dynamodb table for tracking workspace locks. required for s3 backend'
outputs:
  error-message:
    description: "Any errors that occur"
    value: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - id: refs
      name: resolve pr refs
      run: 'node $GITHUB_ACTION_PATH/dist/gh_sha_resolver.js'
      shell: 'bash'
      env:
        gh_token: ${{ inputs.gh_comment_token }}
    - uses: actions/checkout@v3
      with:
        ref: ${{ steps.refs.outputs.head_sha }}
    - name: Add token for private terraform modules
      id: add-gh-private-token
      shell: 'bash'
      # git config --global url."https://${GH_TOKEN}@github.com/${GH_ORG_NAME}".insteadOf "https://github.com/${GH_ORG_NAME}"
      run: |
        git config --local --remove-section http."https://github.com/"
        git config --global url."https://${GH_TOKEN}@github.com".insteadOf "https://github.com"
      env:
        GH_TOKEN: ${{ inputs.gh_pat_token }}
        GH_ORG_NAME: ${{ inputs.gh_org_name }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.0.0
      with:
        cli_config_credentials_token: ${{ inputs.terraform_cloud_api_token }}
        terraform_wrapper: false
    - name: setup aws credentials
      if: inputs.terraform_backend == 's3'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_key }}
        aws-region: us-west-2
    - name: 'Run Script'
      run: 'node $GITHUB_ACTION_PATH/dist/index.js'
      shell: 'bash'
      env:
        gh_comment_token: ${{ inputs.gh_comment_token }}
        terraform_cloud_api_token: ${{ inputs.terraform_cloud_api_token }}
        terraform_org: ${{ inputs.terraform_org }}
        s3_bucket: ${{ inputs.s3_bucket }}
        s3_dynamodb_table: ${{ inputs.s3_dynamodb_table }}

branding:
  icon: 'target'
  color: 'gray-dark'