name: 'PR Deployer'
description: '"ChatOps" deployer using terraform'
inputs:
  gh_comment_token:
    description: 'The token used to add comments (does not need to be PAT)'
    required: true
  gh_pat_token:
    description: 'The token used to read private terraform modules'
    required: true
  gh_org_name:
    description: 'The organization name where private terraform modules are located'
    required: true
  terraform_cloud_api_token:
    description: 'A token for Terraform cloud'
    required: true
  terraform_org:
    description: 'The Terraform cloud organization'
    required: true
outputs:
  error-message:
    description: "Any errors that occur"
    value: ""
runs:
  using: "composite"
  steps:
    #- uses: actions/setup-node@v3
    #  with:
    #    node-version: 18
    - name: 'Resolve PR branch sha1 to use terraform files in PR'
      run: echo ::set-output name=branch::$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')
      shell: 'bash'
      env:
        REPO: ${{ github.repository }}
        PR_NO: ${{ github.event.issue.number }}
        GITHUB_TOKEN: ${{ inputs.gh_comment_token }}
    - uses: actions/checkout@v3
      with:
        ref: ${{ steps.get-branch.outputs.branch }}
    - name: Add token for private terraform modules
      id: add-gh-private-token
      shell: 'bash'
      run: |
        git config --local --remove-section http."https://github.com/"
        git config --global url."https://foo:${GH_TOKEN}@github.com/${GH_ORG_NAME}".insteadOf "https://github.com/${GH_ORG_NAME}"
      env:
        GH_TOKEN: ${{ inputs.gh_pat_token }}
        GH_ORG_NAME: ${{ inputs.gh_org_name }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ inputs.terraform_cloud_api_token }}
        terraform_wrapper: false
    - name: 'Run Script'
      run: 'node $GITHUB_ACTION_PATH/dist/index.js'
      shell: 'bash'
      env:
        gh_comment_token: ${{ inputs.gh_comment_token }}
        terraform_cloud_api_token: ${{ inputs.terraform_cloud_api_token }}
        terraform_org: ${{ inputs.terraform_org }}

branding:
  icon: 'target'
  color: 'gray-dark'