name: 'PR Deployer'
description: '"ChatOps" deployer using terraform'
inputs:
  gh_comment_token:
    description: 'The token used to add comments (does not need to be PAT)'
    required: true
  gh_pat_token:
    description: 'The token used to read private terraform modules'
    required: true
  gh_org_name:
    description: 'The organization name where private terraform modules are located'
    required: true
  terraform_cloud_api_token:
    description: 'A token for Terraform cloud'
    required: true
  terraform_org:
    description: 'The Terraform cloud organization'
    required: true
outputs:
  error-message:
    description: "Any errors that occur"
    value: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - id: refs
      name: resolve pr refs
      run: 'node $GITHUB_ACTION_PATH/dist/gh_sha_resolver.js'
      shell: 'bash'
      env:
        gh_token: ${{ inputs.gh_comment_token }}
    - uses: actions/checkout@v3
      with:
        ref: ${{ steps.refs.outputs.head_sha }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.0.0
      with:
        cli_config_credentials_token: ${{ inputs.terraform_cloud_api_token }}
        terraform_wrapper: false
    - name: 'Run Script'
      run: 'node $GITHUB_ACTION_PATH/dist/index.js'
      shell: 'bash'
      env:
        gh_comment_token: ${{ inputs.gh_comment_token }}
        terraform_cloud_api_token: ${{ inputs.terraform_cloud_api_token }}
        terraform_org: ${{ inputs.terraform_org }}

branding:
  icon: 'target'
  color: 'gray-dark'
